### ISSUE TITLE
"Unsupported major.minor version 52.0"

### ISSUE THREAD

**Issue by geecko86** [uPhyca/GAlette#37]
That's the error I'm getting when using 

> classpath 'com.uphyca.galette:galette-plugin:0.9.14'

According to the quick research I just did, it's because you compiled it with Java 8. Android only supports Java 6 or 7.

**Comment by esmasui** [comment]
Thank you for your report. I'll fixed it and release it as the next version soon.

**Comment by esmasui** [comment]
@geecko86 
We've uploaded the latest build to Maven Central.
It may take a few hours to complete,
thank you.
